export const aboutMe = `
**Hi everyone!** I'm **Irfan Nurghiffari Muhajir**, you can call me **Irfan**. I grew up in Tangerang, which is one of the satellite cities of Jakarta. Currently I'm a Software Engineering graduate from Universitas Pendidikan Indonesia. I started my study in 2019 and graduated in 2023. But, i was an Industrial Engineering student in 2018 before i decided to move.

I focus much of my time in college to learn about software engineering & frontend web development using React & NextJS. I also regularly use cloud platforms such as AWS, Azure & GCP and have experience in using Kubernetes & Red Hat Openshift. I love exploring stuff about technology.

I'm part of Red Hat's team as a Class Assistant & Help desk in <u>**[Digital Talent Scholarship](https://digitalent.kominfo.go.id/)**</u> held by Kementrian Kominfo for 3 years. I'm also part of <u>**[Ramaniya](https://ramaniya.id/)**</u> as a freelance Information Technology Staff in 2021. I'm one of the alumni of <u>**[Generasi Gigih](https://www.anakbangsabisa.org/generasi-gigih/)**</u> held by Yayasan Anak Bangsa Bisa & GoTo Group at Frontend Engineering Track.

Lately I have been doing internships to further enhance my knowledge about having a career in the professional tech industry. My first internship is with Sagara Technology, which is a software development house based in Jakarta & Bandung. After that, I'm taking part as one of the interns at <u>**[PT Bank Mandiri (Persero) Tbk](https://bankmandiri.co.id)**</u> in Digital Talent Program held by the company in collaboration with Ministry of Education's Kampus Merdeka program. Which leads me to learn more about IT & tech in the banking industry, which is one of my interest outside of tech. At the start of 2023, after quite a long recruitment process, I finally get an offer from <u>**[PT Bank Central Asia Tbk](https://bca.co.id)**</u>, or more widely known as BCA, to join #ITBCA's Modernization team as Application Developer intern.
`
